---
vector_arch:
  armv7l: armv7hl
  aarch64: aarch64
  x86_64: x86_64

vector_repo: https://yum.vector.dev/stable/vector-0/$basearch/
vector_repo_key:
  - https://keys.datadoghq.com/DATADOG_RPM_KEY_CURRENT.public
  - https://keys.datadoghq.com/DATADOG_RPM_KEY_B01082D3.public
  - https://keys.datadoghq.com/DATADOG_RPM_KEY_FD4BF915.public
vector_repo_gpgcheck: true
