---

# vector configuration file
vector_template: vector.yaml.j2
vector_config_file: /etc/vector/vector.yaml

# vector groups
# vector_groups: []

# install vector from repo
vector_install_from_repo: false

# vector package name
vector_package: vector
